### ISSUE TITLE
Parameter issue

### ISSUE THREAD

**Issue by Blissgig** [isaacrlevin/LifxCloudClient#4]
EDIT:  I was obviously an idiot.  Took me a day but...

Example for others (in ref to Selector)
                Selector.LightId selector = new Selector.LightId(light.Id);

                var result = await lifxCloudClient.SetState(selector,
                    new LifxCloud.NET.Models.SetStateRequest
                    {
                        Power = LifxCloud.NET.Models.PowerState.On,
                        Brightness = 1,
                        Duration = 1,
                        Color = "yellow saturation:1"
                    });

**Comment by isaacrlevin** [comment]
I am sorry, what is the issue. Not quite understanding
